apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: borotriestocode/product-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3003
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        env:
        - name: MONGO_URL
          value: mongodb://product-mongodb:27017/products
        - name: KAFKA_BROKER
          value: kafka:9092
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
