order-mongodb:
  nameOverride: "order-mongodb"
  replicaCount: 2

  image:
    repository: mongo
    pullPolicy: IfNotPresent
    tag: 4.4.6

  service:
    type: ClusterIP
    port: 27017

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  persistence:
    enabled: true
    size: 1Gi

customer-mongodb:
  nameOverride: "customer-mongodb"
  replicaCount: 2

  image:
    repository: mongo
    pullPolicy: IfNotPresent
    tag: 4.4.6

  service:
    type: ClusterIP
    port: 27017

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  persistence:
    enabled: true
    size: 1Gi

product-mongodb:
  nameOverride: "product-mongodb"
  replicaCount: 2

  image:
    repository: mongo
    pullPolicy: IfNotPresent
    tag: 4.4.6

  service:
    type: ClusterIP
    port: 27017

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  persistence:
    enabled: true
    size: 1Gi

kafka:
  kafka:
    image: wurstmeister/kafka
    tag: latest
    port: 9092

  zookeeper:
    image: wurstmeister/zookeeper
    tag: latest
    port: 2181

  kafka-ui:
    image: provectuslabs/kafka-ui
    tag: latest
    port: 8080

kafka-ui:
  kafka:
    brokers:
      - kafka:9092  

redis:
  replicaCount: 1

  image:
    repository: redis
    pullPolicy: IfNotPresent
    tag: latest

  service:
    type: ClusterIP
    port: 6379

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}



