apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: borotriestocode/order-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        env:
        - name: MONGO_URL
          value: mongodb://order-mongodb:27017/orders
        - name: KAFKA_BROKER
          value: kafka:9092
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
